modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="MIT"
[[mods]] #mandatory
modId="differentperspective" #mandatory
<<<<<<< Updated upstream
version="1.19-1.1.0" #mandatory
=======
version="1.19-1.1.1" #mandatory
>>>>>>> Stashed changes
displayName="Different Perspective Mod" #mandatory
logoFile="logo.png" #optional
credits="" #optional
authors="Vaihacky" #optional

description='''
Different Perspective Mod allows you to change perspective of your camera without the need of cycling through all of them
'''

[[dependencies.differentperspective]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="CLIENT"
    
[[dependencies.differentperspective]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="CLIENT"
