modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]] #mandatory
modId="differentperspective"
version="1.18.2-1.0.3" #mandatory
displayName="Different Perspective Mod"
logoFile="logo.png"
credits=""
authors="Vaihacky"

description='''
Different Perspective Mod allows you to change perspective of your camera without the need of cycling through all of them
'''

[[dependencies.differentperspective]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.differentperspective]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="CLIENT"
